bind: 127.0.0.1:27141
top_n: 10
refresh_seconds: 300
encoded_subscription: true
prioritize_stability: false
fetch_timeout_ms: 15000
fetch_concurrency: 4
max_subscription_bytes: 16777216
probe:
  mode: active
  sing_box_path: C:\Users\Administrator\Desktop\v2rayN-windows-64\bin\sing_box\sing-box.exe
  connect_timeout_ms: 10000
  active_timeout_ms: 10000
  startup_timeout_ms: 10000
  concurrency: 16
  batch_size: null
  test_url: https://www.gstatic.com/generate_204
  accepted_statuses:
  - 204
  - 200
  download_url: null
  download_bytes_limit: 1048576
sharing:
  enabled: true
  require_token: false
  token: ''
subscriptions:
- name: first
  url: https://raw.githubusercontent.com/zieng2/wl/main/vless_universal.txt
  enabled: true
  priority: 1
- name: second
  url: https://raw.githubusercontent.com/masir-sefid/Sub/main/@Masir_Sefid.txt
  enabled: true
  priority: 2
